### PR TITLE
Add GitHub action workflow

### PR DESCRIPTION
**Pull request by avdev4j**
close https://github.com/entando/entando-blueprint/issues/100

This is a first step that only test the generator himself. Adding matrix configuration need to be discussed and prepare before.

### CODE REVIEW

**Comment by avdev4j** [comment]
oh and yes, this workflow should fail while this PR is not merged
https://github.com/entando/entando-blueprint/pull/99

and this issue is not resolved
https://github.com/entando/entando-blueprint/issues/102

**Comment by joewhite101** [comment]
@ampie What do you think about using GitHub actions for this one? Seems like an easier fit than JenkinsX and we can get it going quickly. But don't want to add this if it fractures us too much on the CI side.

**Comment by avdev4j** [comment]
Well, it's depend on the GitHub kind of account you have but you have free minutes runners reset every month.

> Product | Storage | Minutes (per month)
> -- | -- | --
> GitHub Free | 500 MB | 2,000
> GitHub Pro | 1 GB | 3,000
> GitHub Free for organizations | 500 MB | 2,000
> GitHub Team | 2 GB | 3,000
> GitHub Enterprise Cloud | 50 GB | 50,000

https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions

**Comment by joewhite101** [comment]
Looks good to me. Lets see how this goes.

**Review by joewhite101 — APPROVED** [review]

**Pull request merged**
