### PR TITLE
Add missing .gitignore to the detailsWidget

### PR DESCRIPTION
**Pull request by nshaw**

### CODE REVIEW

**Comment by avdev4j** [comment]
Unless this file fix a bug for the 6.3 release, I suggest to wait to the https://github.com/entando/entando-blueprint/pull/112 to be merged because we will need to update the files array and the expectedFiles test array.

This PR deeply change how we deals with files in entity-server. Even this file will belong to another subgen specialized for MFE.

**Comment by nshaw** [comment]
@avdev4j , I was hoping to have this in 6.3 since it negatively affects the dev experience. The missing .gitignore means all of the build files show up as changes as soon as you touch anything and that confuses new users. This file exists for the other two widgets as-is.

**Comment by avdev4j** [comment]
seems legit, let's merge that and I will update the PR https://github.com/entando/entando-blueprint/pull/112

**Comment by nshaw** [comment]
> seems legit, let's merge that and I will update the PR #112

@avdev4j , cool, thanks.  Looks like I still need an approval and we can close this out.

**Review by avdev4j — APPROVED** [review]

**Comment by avdev4j** [comment]
Done here: https://github.com/entando/entando-blueprint/pull/112/commits/ce5e058d67addf4c3eae24ef7e80b587b3ab00b2 ;)

**Pull request merged**
