### PR TITLE
Ecs 463/remove old bundle files

### PR DESCRIPTION
**Pull request by avdev4j**
Since the OCE V5 doesn't need any bundle descriptors, and shell scripts from the micro app, just remove them

- [X] remove main bundle descriptor and microservice
- [X] remove shell scripts
- [x] remove mfe bundle descriptors
- [x] remove needle code to inject references in descriptors
- [x] Remove question about bundle name
- [x] Remove the common sub-generator because it was handed the .gitignore only that added rules for bundle descriptors

### CODE REVIEW

**Comment by avdev4j** [comment]
@w-caffiero-entando @nshaw 
Do we agree the generator should not ask for the bundle name anymore? I suppose the CLI handles that now and stores it into the JSON file.

**Comment by nshaw** [comment]
@avdev4j no need for that question unless the blueprint will be calling ent bundle init directly. Either we have the user do it and then the blueprint fills in the pieces, or the blueprint creates a new project from scratch including the init step.

**Comment by avdev4j** [comment]
@nshaw but I think we should decouple the blueprint and the CLI. The CLI does the init, the CLI calls the blueprint, and the blueprint generates the files.
So, the blueprint doesn't know the CLI and is totally out of the scope of the bundle, the generated project will just fill the space defined by the CLI to create a microservice component.

**Comment by nshaw** [comment]
@avdev4j sounds good to me. I agree decoupling is better.

**Comment by avdev4j** [comment]
perfect @nshaw, so here we go, this PR is ready for a review. I will add you with more people as reviewers

**Pull request merged**
