### PR TITLE
ENG-4226 merge 7.1

### PR DESCRIPTION
**Pull request by alepintus**

### CODE REVIEW

**Comment by avdev4j** [comment]
hi @alepintus 
please note there is something missing here: the version updating in the package.json file. I guess this branch has been created from the tag. Do you think we can update it nevertheless?

**Comment by avdev4j** [comment]
We can close this one since the PRs have been previously merged into both 7.1 branch and develop

**Comment by alepintus** [comment]
Hi @avdev4j talking with @zonia3000, @antromeo and @cecchisandrone about this PR we were thinking to merge this commits to have the same history and to avoid to have these commits if we have to merge again from the release branch.
WDYT?

**Comment by avdev4j** [comment]
yes, this is true. let's do it. Next time maybe do one PR to develop then to the release branch so we'll have to do merge that kind of merge commits.
In this case, it's mostly because we did both the dev and the release in a short time frame.

**Pull request merged**
